/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit a camera's label, zone and welfare notification policy — UNAUTHENTICATED, and off by default
         * @description Change what a camera is called, which zone it is grouped into, and what its
         *     welfare concerns notify a human about.
         *
         *     ### This endpoint is not authenticated
         *
         *     **Phase 1B ships no authentication of any kind.** The console's login screen
         *     is a shell, JWT arrives in Phase 1C, and until then anything that can open a
         *     TCP connection to this port can call this. Every other endpoint is a read, so
         *     reaching the port has so far cost an attacker information; this one is a
         *     write, and a persisted one. An anonymous caller can rename a camera to another
         *     camera's name and re-zone it into another wing — which is to say, make the
         *     console's account of *where an incident happened* wrong, in a custodial
         *     setting, permanently, because the change is written to `cameras.json` and
         *     survives the restart that would otherwise undo it.
         *
         *     That is why it is **off unless a deployment turns it on**
         *     (`SENTINEL_ENABLE_CAMERA_WRITES=true`) and answers 403 otherwise, and why a
         *     deployment that turns it on should also bind the engine to localhost or put an
         *     authenticating reverse proxy in front of it. `GET /cameras` reports the current
         *     posture as `config_writable`. See `docs/operations.md`.
         *
         *     ### What can be edited, and what cannot
         *
         *     Editable at runtime, applied to the running camera and written to
         *     `cameras.json` before this returns:
         *
         *     * `label` — the display name. Trimmed, non-empty, at most 120 characters.
         *     * `zone` — `room`, `corridor`, `dayroom`, or `null` to ungroup. Omitting the
         *       field and sending `null` are different instructions.
         *     * `notify_on` — which welfare concern kinds notify a human, as a whole
         *       replacement list. `[]` means never notify from this camera and is a real
         *       edit, not an empty one; `null` is rejected because `[]` already says it.
         *     * `notify_min_confidence` — `possible` or `likely`, the lowest tier that may
         *       notify. There is no `certain`: one still frame cannot earn it.
         *     * `clip_preroll_seconds`, `clip_postroll_seconds`,
         *       `summary_interval_seconds` — per-camera overrides of the engine-wide clip
         *       bounds and the profile's summary interval. **Omitting one and sending
         *       `null` are different instructions**, as with `zone`: omit to leave the
         *       override alone, send `null` to drop it and go back to the default. Pre-roll
         *       may be `0` (no lead-in is a real choice); the other two must be above zero.
         *
         *     Every one of them comes back in the response as it was stored, so a console
         *     renders what the file now says rather than what it hoped it would say.
         *
         *     **Not editable, and rejected with 422 rather than ignored** — the response's
         *     `restart_required_fields` names them:
         *
         *     * `url` — changing the source means tearing down the running `CameraRunner`,
         *       its buffered pre-roll and any clip mid-recording, and building a new source
         *       in their place. It is a camera restart, not an edit. Separately, an RTSP URL
         *       routinely carries credentials, so an unauthenticated API neither accepts nor
         *       returns it.
         *     * `profile` — the escalation policy, which the gate is part-way through
         *       applying (cooldowns, a token bucket with state). Swapping it mid-flight has
         *       no defensible semantics.
         *
         *     Both are edited by changing `cameras.json` and restarting the engine.
         *
         *     ### Atomicity
         *
         *     The edit is validated against the whole document, written to a temporary file,
         *     `fsync`ed, and renamed into place. It is never half-applied: a request that
         *     would produce a file the engine could not load at its next startup is refused
         *     outright, and everything the file holds that this engine has no model of —
         *     comment keys, other cameras, fields added later — is preserved byte-for-byte
         *     in meaning. The in-memory camera is only updated *after* the file is on disk,
         *     and from what the file now says, so the two cannot disagree.
         */
        patch: operations["update_camera_cameras__camera_id__patch"];
        trace?: never;
    };
    "/cameras/{camera_id}/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Describe Camera Now */
        post: operations["describe_camera_now_cameras__camera_id__describe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent events for one camera (volatile console cache — NOT the event store)
         * @description Recent anomaly events for one camera, plus the latest scene description.
         *
         *     **This is a volatile, bounded, in-memory view for the operator console. It is not
         *     the event store and it is not an audit trail.** The durable record is the anomaly
         *     event published to RabbitMQ and written down by the Phase 1C consumer. What this
         *     endpoint reads is a per-camera ring inside the running engine that is emptied by
         *     any restart and that silently discards the oldest entry once the camera has
         *     produced more than `capacity` events. The absence of an event here means "not in
         *     the last `capacity` events of this process run" — never "did not happen". Anyone
         *     reconciling a custodial incident must go to the store, not here.
         *
         *     The ring is per camera rather than global on purpose, so that a busy camera can
         *     only evict its own history and never a quiet camera's.
         *
         *     `latest` is the last element of `events`, lifted out for the live scene panel and
         *     read from the same snapshot, so the panel and the chart cannot disagree about
         *     which event is newest. `latest_description_state` distinguishes the three cases a
         *     console must not confuse: `none` (nothing assembled yet in this process),
         *     `available` (a real vision-model description), and `unavailable` (the vision model
         *     could not answer, and `latest.description` is a metadata-derived stand-in rather
         *     than a description of the scene).
         *
         *     An unknown camera is a 404, the same mapping every other camera route uses. A
         *     configured camera that has not escalated yet is a 200 with an empty `events` list.
         */
        get: operations["get_camera_events_cameras__camera_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Telemetry */
        get: operations["get_camera_telemetry_cameras__camera_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live event stream (SSE) over the same volatile ring — NOT the event store
         * @description Every camera's anomaly events, pushed as they happen (spec §6.2, bridged).
         *
         *     **The same volatile, bounded, in-memory ring `GET /cameras/{camera_id}/events`
         *     serves — not the event store and not an audit trail.** The durable record is the
         *     anomaly event published to RabbitMQ and written down by the Phase 1C consumer.
         *     Everything this stream can send is held in engine memory, is lost on restart, and
         *     is silently evicted once a camera has produced more than `capacity` events.
         *
         *     **What a reconnect can and cannot give you.** Every connection opens with a
         *     `backlog` frame holding what the ring currently has, then continues live. There is
         *     no gap between the two and no duplicate across them. But the ring is bounded, so a
         *     client that was disconnected long enough for a camera to produce more than its
         *     ring holds **has permanently missed those events on this endpoint** — they are in
         *     RabbitMQ, and this endpoint will never show them. That is why no `id:` field is
         *     sent and `Last-Event-ID` is not honoured: resuming from an offset the engine may
         *     no longer hold would promise a continuity it cannot keep. Reconnect, take the new
         *     backlog as the current window, and go to the store for anything older.
         *
         *     **Duplicates and updates.** An `event_id` may arrive more than once: an event is
         *     re-sent when something about it changes, currently when its clip finishes and
         *     `clip_uri` appears. Merge by `event_id`, keeping the copy with the higher
         *     `sequence`. Two copies with the same `sequence` are the same copy.
         *
         *     **Falling behind.** A client that stops reading is buffered up to a fixed bound
         *     and then cut off with an `overflow` frame rather than being allowed to grow the
         *     engine's memory. Reconnect; the fresh backlog is more current than the queue that
         *     was dropped.
         *
         *     **Shutdown.** The engine closes every stream as it shuts down, so a client sees a
         *     clean end of response rather than a connection that hangs until a proxy times it
         *     out.
         */
        get: operations["stream_events_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CameraEditRequest
         * @description A partial edit to one camera's record: its label, its zone, and its welfare
         *     notification policy, in any combination.
         *
         *     Partial on purpose — a console changing a label must not have to restate a zone
         *     it is not touching, because restating it is how one operator's window silently
         *     reverts another's change.
         *
         *     **Only the runtime-editable fields are accepted, and the rest are rejected
         *     rather than ignored.** `extra="forbid"` means a body carrying `url` or
         *     `profile` is a 422 naming the field, not a 200 that quietly dropped it. That
         *     is the whole reason the model is strict: the failure this endpoint must never
         *     have is an operator re-pointing a camera at a new stream, being told it
         *     worked, and watching the old stream for a week.
         */
        CameraEditRequest: {
            /**
             * Clip Postroll Seconds
             * @description Seconds of video to keep recording after a notified concern's keyframe, for this camera only. `null` reverts it to the engine-wide default; omitting the field leaves it as configured. Must be greater than zero — a clip that ends where it begins is not a shorter clip, it is no clip.
             */
            clip_postroll_seconds?: number | null;
            /**
             * Clip Preroll Seconds
             * @description Seconds of buffered video to keep before a notified concern's keyframe, for this camera only. `null` reverts it to the engine-wide default; omitting the field leaves it as configured — **the two are different instructions**, the same way `zone`'s are. `0` is allowed and means no lead-in at all, which is why this bound is `>= 0` where the other two durations are `> 0`.
             */
            clip_preroll_seconds?: number | null;
            /**
             * Label
             * @description The camera's new display name. Trimmed; must be non-empty after trimming. Omit the field to leave the label alone — `null` is not a label and is rejected.
             */
            label?: string | null;
            /** @description The lowest confidence tier that may notify. `likely` is the engine's default; `possible` widens it to everything the model flags at all, which on an ordinary day is most of its opinions. Omit to leave the threshold alone; `null` is rejected, because a camera has no 'no threshold' state. There are exactly two tiers and there is no `certain` — see `domain/welfare.py`: one still frame cannot earn it. */
            notify_min_confidence?: components["schemas"]["Confidence"] | null;
            /**
             * Notify On
             * @description Which welfare concern kinds this camera notifies a human about, replacing whatever is configured now — this is a whole new list, not an addition to the old one. **`[]` means never notify from this camera**, which is a real instruction and not an empty edit: it silences one camera without turning welfare monitoring off anywhere else. Omit the field to leave the routing alone; `null` is rejected, because `[]` already covers the only thing it could have meant. A kind outside the enum is a 422 rather than a silent narrowing of the list — a typo'd kind is a concern the operator meant to be told about and would not be.
             */
            notify_on?: components["schemas"]["ConcernKind"][] | null;
            /**
             * Summary Interval Seconds
             * @description How often this camera's periodic summary runs. `null` reverts it to the camera profile's interval; omitting the field leaves it as configured. Distinct from `profile.summary_interval_seconds`, which is restart-only — this is the runtime-editable override of it, and it wins where both are set.
             */
            summary_interval_seconds?: number | null;
            /** @description The camera's new zone, or `null` to ungroup it. Unlike `label`, `null` here is a real instruction, so **omitting the field and sending null mean different things**: omit to leave the grouping alone, send null to remove it. A value outside the enum is a 422 — the same fail-loud `load_cameras` applies at startup, because a typo'd zone is a camera the operator meant to group and silently did not. */
            zone?: components["schemas"]["Zone"] | null;
        };
        /**
         * CameraEditResponse
         * @description The camera's record as `cameras.json` now holds it, after a successful edit.
         *
         *     The whole record rather than an acknowledgement: a console that has just
         *     written should render what was stored, not what it hoped was stored.
         */
        CameraEditResponse: {
            /** Camera Id */
            camera_id: string;
            /**
             * Clip Postroll Seconds
             * @description As `clip_preroll_seconds`: the stored override, or null for the default.
             */
            clip_postroll_seconds: number | null;
            /**
             * Clip Preroll Seconds
             * @description The stored per-camera override, or null when this camera uses the engine-wide default. Null here is the answer to 'what is stored', not a report of the effective value — the default in force is not this endpoint's to state.
             */
            clip_preroll_seconds: number | null;
            /** Label */
            label: string;
            /** @description The stored confidence threshold. Never null: a camera always has one. */
            notify_min_confidence: components["schemas"]["Confidence"];
            /**
             * Notify On
             * @description The concern kinds this camera will notify on, as stored — always the full list, never a diff, and sorted so two reads of the same record compare equal. A camera whose file says nothing about `notify_on` lists every kind here, because that is what saying nothing means. `[]` means this camera notifies nobody.
             */
            notify_on: components["schemas"]["ConcernKind"][];
            /**
             * Persisted
             * @description Always true, and present so it cannot be overlooked: this edit was written to the engine's `cameras.json` before this response was sent, and survives a restart. An edit that could not be written is an error response, never a 200 with this set to false.
             * @default true
             * @constant
             */
            persisted: true;
            /**
             * Restart Required Fields
             * @description Fields of the camera record that this endpoint will not change at all: they are stored in `cameras.json`, honoured at startup, and require editing that file and restarting the engine. `url` because changing it means tearing down the running camera and building a new source (and because an RTSP URL routinely carries credentials, which an unauthenticated API must not move in either direction); `profile` because it is the escalation policy the gate is part-way through applying. Sending either one is a 422, not a silent drop — a console should show them as read-only and say why, not offer a control that does nothing.
             */
            restart_required_fields?: string[];
            /**
             * Summary Interval Seconds
             * @description The stored override, or null when this camera falls back to its profile's `summary_interval_seconds`.
             */
            summary_interval_seconds: number | null;
            /** @description The stored zone, or null when the camera is ungrouped. */
            zone: components["schemas"]["Zone"] | null;
            /** @description Derived from `zone`, exactly as on `CameraStatus`. Null when `zone` is. */
            zone_kind: components["schemas"]["ZoneKind"] | null;
        };
        /**
         * CameraEventsResponse
         * @description A **volatile, bounded, in-memory view for the operator console. Not the event
         *     store, and not an audit trail.**
         *
         *     The durable record of what happened is RabbitMQ plus the Phase 1C consumer that
         *     writes it down. This endpoint reads an in-process ring that (a) is emptied by any
         *     restart of the engine, and (b) silently discards a camera's oldest entry once that
         *     camera has produced more than `capacity` events. An absent event here therefore
         *     means "not in the last `capacity` events of this process run" and never "did not
         *     happen". Do not reconcile against it, do not report from it, and do not use it to
         *     establish that nothing occurred.
         */
        CameraEventsResponse: {
            /** Camera Id */
            camera_id: string;
            /**
             * Capacity
             * @description The per-camera ring bound. Once `returned` reaches it, every new event silently evicts the oldest — published here so a console can say how much history it is not showing.
             */
            capacity: number;
            /**
             * Events
             * @description Retained events, oldest first — plot them in this order.
             */
            events: components["schemas"]["RecentEventEntry"][];
            /** @description The most recent event, i.e. the last element of `events`, lifted out for the live scene panel. Read from the same snapshot as `events`, so the panel and the chart can never disagree about which event is newest. Null exactly when `latest_description_state` is 'none'. */
            latest: components["schemas"]["RecentEventEntry"] | null;
            /**
             * Latest Description State
             * @description Whether the live panel has a real description ('available'), a stand-in because the vision model could not answer ('unavailable'), or nothing at all yet ('none').
             * @enum {string}
             */
            latest_description_state: "none" | "available" | "unavailable";
            /**
             * Returned
             * @description How many events this response carries.
             */
            returned: number;
            /**
             * Volatile
             * @description Always true, and present so it cannot be overlooked: this history is held in engine memory only and does not survive a restart. The event store is elsewhere.
             * @default true
             * @constant
             */
            volatile: true;
        };
        /** CameraStatus */
        CameraStatus: {
            /** Camera Id */
            camera_id: string;
            /**
             * Clip Postroll Seconds
             * @description As `clip_preroll_seconds`: the stored override, or null for the default.
             */
            clip_postroll_seconds: number | null;
            /**
             * Clip Preroll Seconds
             * @description The stored per-camera override, or null when this camera follows the engine-wide default. **Null is the answer to 'what is stored', not a report of the effective value** — the same meaning `CameraEditResponse` gives it. A console that resolved it locally and then submitted what it showed would pin the camera to a number nobody chose and opt it out of any later change to the default.
             */
            clip_preroll_seconds: number | null;
            /** Detections Run */
            detections_run: number;
            /** Discontinuities */
            discontinuities: number;
            /** Escalations */
            escalations: number;
            /** Escalations Dropped */
            escalations_dropped: number;
            /** Frames Dropped */
            frames_dropped: number;
            /** Frames Seen */
            frames_seen: number;
            /**
             * Label
             * @description The camera's display name, from `cameras.json`; defaults to `camera_id` when the file gives none. Editable at runtime via `PATCH /cameras/{camera_id}` — read it back from here after a write to see what the engine is actually using.
             */
            label: string;
            /** Last Escalation At */
            last_escalation_at: number | null;
            /** Last Frame At */
            last_frame_at: number | null;
            /** @description The stored confidence threshold. Never null: a camera always has one. */
            notify_min_confidence: components["schemas"]["Confidence"];
            /**
             * Notify On
             * @description The concern kinds this camera will notify a human about, as stored — always the full list, never a diff, and sorted so two reads of the same record compare equal. A camera whose file says nothing about `notify_on` lists every kind, because that is what saying nothing means. `[]` means this camera notifies nobody, which is a stored choice rather than an unset field: **render it as muted, not as unconfigured.** Identical in meaning to `CameraEditResponse.notify_on`, so a console can compare what it wrote against what it later reads here.
             */
            notify_on: components["schemas"]["ConcernKind"][];
            /**
             * Summary Interval Seconds
             * @description The stored override, or null when this camera falls back to its profile's `summary_interval_seconds`.
             */
            summary_interval_seconds: number | null;
            /** @description Which space this camera watches — the field cameras are grouped by. Null means ungrouped: nobody has assigned this camera a zone. Null is not a group; do not render it as one alongside the real zones. */
            zone?: components["schemas"]["Zone"] | null;
            /** @description The coarse grouping `zone` falls into, derived from it and never stored separately, so the two cannot disagree. Null exactly when `zone` is null. */
            zone_kind?: components["schemas"]["ZoneKind"] | null;
        };
        /** CamerasResponse */
        CamerasResponse: {
            /** Cameras */
            cameras: components["schemas"]["CameraStatus"][];
            /**
             * Config Writable
             * @description Whether `PATCH /cameras/{camera_id}` will do anything on this deployment. False — the default — means the write endpoint answers 403 and the camera record can only be changed by editing `cameras.json` and restarting. This engine has **no authentication**, so writes are opt-in per deployment (`SENTINEL_ENABLE_CAMERA_WRITES`); see the PATCH operation's description. Published here so a console can render the record read-only rather than offering controls that will 403.
             */
            config_writable: boolean;
        };
        /**
         * ConcernKind
         * @description What the VLM's welfare-focused prompt asks the frame to be checked for.
         * @enum {string}
         */
        ConcernKind: "collapse" | "altercation" | "self_harm" | "medication" | "distress" | "other";
        /**
         * Confidence
         * @description How sure a single still frame can honestly make the model.
         *
         *     Deliberately two members, not three: see the module docstring for why
         *     there is no `CERTAIN`.
         * @enum {string}
         */
        Confidence: "possible" | "likely";
        /** DescribeResponse */
        DescribeResponse: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Models */
            models: components["schemas"]["ModelHealth"][];
            /** Status */
            status: string;
        };
        /** ModelHealth */
        ModelHealth: {
            /** Detail */
            detail: string;
            /** Key */
            key: string;
            /** State */
            state: string;
            /** Vram Mib */
            vram_mib: number;
        };
        /**
         * RecentEventEntry
         * @description One event as the console sees it — a projection of the published anomaly event,
         *     not the event itself.
         *
         *     The same shape is served three ways: in `GET /cameras/{camera_id}/events`, in the
         *     `backlog` array that opens `GET /events/stream`, and in each live frame on that
         *     stream. One shape on purpose, so a console can merge all three into one list
         *     keyed by `event_id`, keeping the copy with the highest `sequence`.
         */
        RecentEventEntry: {
            /**
             * Camera Id
             * @description Which camera produced this. Redundant on the per-camera endpoint, and essential on `/events/stream`, which carries every camera's events.
             */
            camera_id: string;
            /**
             * Clip Uri
             * @description Where this event's clip was written, or null. Null covers three different situations and is not by itself evidence of any one of them: no clip was being recorded, the clip has not finished uploading yet (it lands shortly after the event, and the event is then re-sent on the stream with a higher `sequence`), or the clip failed to write. An event is never withheld because its clip failed — spec §9 — so a null here says nothing at all about whether the event happened.
             */
            clip_uri: string | null;
            /**
             * Description
             * @description The scene description — unless `description_unavailable` is true, in which case this is a metadata-derived stand-in and not a description of the scene.
             */
            description: string;
            /**
             * Description Unavailable
             * @description True when the vision model could not answer and this event was assembled from cheap signals alone. Never conflate it with the absence of an event.
             */
            description_unavailable: boolean;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Labels */
            labels: string[];
            /**
             * Occurred At
             * @description Unix epoch seconds (UTC, fractional). Sort and plot on this — it is the same field, with the same meaning, as the published event's `occurred_at`.
             */
            occurred_at: number;
            /**
             * Reason
             * @description Which of the seven escalation triggers fired.
             */
            reason: string;
            /**
             * Sequence
             * @description This version's position in the engine's write order for the recent-event ring — a de-duplication key, never a sort key. An event can be sent more than once with the same `event_id`: it is re-sent when something about it changes, currently when its clip finishes uploading and `clip_uri` appears. The copy with the higher `sequence` is the newer one; two copies with the same `sequence` are the same copy. Per process and monotonic — it restarts from zero when the engine does, exactly like the ring itself, so never persist it or compare it across a restart.
             */
            sequence: number;
            /**
             * Severity
             * @description The band `threat_score` falls in.
             */
            severity: string;
            /**
             * Source Timestamp
             * @description The camera source's own timeline for the same instant. Correlates with a clip's pts; meaningful only within one process run for one camera, so never sort or display on it.
             */
            source_timestamp: number | null;
            /** Suggested Action */
            suggested_action: string;
            /**
             * Threat Score
             * @description The threat value, 0.0 to 1.0.
             */
            threat_score: number;
            /** Track Ids */
            track_ids: number[];
            /**
             * Welfare Concerns
             * @description What the vision model said about a person's wellbeing in this frame — **an opinion about one still frame, not a detector's finding.** Empty means it reported nothing, which is not evidence that nothing happened; when `description_unavailable` is true it means the model could not answer at all. Always a list, never absent.
             *
             *     **Not filtered by the camera's `notify_on`.** That policy decides which concerns are pushed to somebody who is *not* watching the console; every concern the model reported appears here, so muting a camera silences its notifications without also blinding the operator reading its events.
             */
            welfare_concerns: components["schemas"]["WelfareConcernEntry"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WelfareConcernEntry
         * @description One welfare concern as the console reads it.
         *
         *     The wire form of `domain.welfare.WelfareConcern`, minus the assessment's
         *     `basis` — which has exactly one value today, so repeating it on every concern
         *     would be noise. A second basis is a deliberate change that rewrites the
         *     routing rule and the console's wording together (ADR 10), not something a
         *     consumer should be silently reading for.
         */
        WelfareConcernEntry: {
            /** @description The model's own uncertainty, not a thresholded score. There are exactly two tiers and there is no `certain`: one still frame cannot earn it. */
            confidence: components["schemas"]["Confidence"];
            /**
             * Evidence
             * @description What the model says it actually saw, in its own words — **unless** `evidence_stated` is false, in which case this is a fixed placeholder and the model described nothing. Never render one as the other.
             */
            evidence: string;
            /**
             * Evidence Stated
             * @description False when the model named this concern but described nothing. The concern still routes and still displays — a concern without a stated reason is not a concern that did not happen — but a reader weighing it needs to know the difference.
             */
            evidence_stated: boolean;
            /** @description Which of the five things the prompt asks about, or `other`. */
            kind: components["schemas"]["ConcernKind"];
        };
        /**
         * Zone
         * @description The space a camera watches. The recorder's `space_type` vocabulary, exactly.
         *
         *     Deliberately the recorder's four-camera vocabulary rather than a new one: the two
         *     systems watch the same building, and a console that shows both must not have to
         *     translate. Extending it is a one-line addition here plus its entry in `_KINDS`,
         *     which `tests/domain/test_zone.py` requires for every member.
         * @enum {string}
         */
        Zone: "room" | "corridor" | "dayroom";
        /**
         * ZoneKind
         * @description The coarse privacy/behaviour split a `Zone` falls into.
         *
         *     Derived from `Zone`, never stored: see this module's docstring. `StrEnum` so it
         *     serialises as `"room"` / `"common_area"` with no encoder of its own.
         * @enum {string}
         */
        ZoneKind: "room" | "common_area";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cameras_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CamerasResponse"];
                };
            };
        };
    };
    update_camera_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEditResponse"];
                };
            };
            /** @description Camera writes are disabled on this deployment, which is the default. Set `SENTINEL_ENABLE_CAMERA_WRITES=true` on the engine to enable them, having read the warning in this operation's description first. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No camera with this id is configured in the running engine. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `cameras.json` cannot be edited as it currently stands — most often because the file has been changed by hand since the engine started and no longer contains this camera. Nothing was written. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description The camera file could not be written. Nothing was changed. */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    describe_camera_now_cameras__camera_id__describe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DescribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_events_cameras__camera_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_telemetry_cameras__camera_id__telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_events_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open `text/event-stream`. Frames: `event: backlog` once, carrying a JSON array of RecentEventEntry (oldest first, possibly empty); then `event: anomaly`, one RecentEventEntry each, as they are assembled; `event: overflow` if this client fell too far behind, after which the stream ends and reconnecting is the recovery; and `: keepalive` comment lines on an idle stream. No `id:` field is sent and `Last-Event-ID` is not honoured — see the description. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description The engine has not finished starting; retry shortly. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
