/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cameras */
        get: operations["list_cameras_cameras_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/describe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Describe Camera Now */
        post: operations["describe_camera_now_cameras__camera_id__describe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent events for one camera (volatile console cache — NOT the event store)
         * @description Recent anomaly events for one camera, plus the latest scene description.
         *
         *     **This is a volatile, bounded, in-memory view for the operator console. It is not
         *     the event store and it is not an audit trail.** The durable record is the anomaly
         *     event published to RabbitMQ and written down by the Phase 1C consumer. What this
         *     endpoint reads is a per-camera ring inside the running engine that is emptied by
         *     any restart and that silently discards the oldest entry once the camera has
         *     produced more than `capacity` events. The absence of an event here means "not in
         *     the last `capacity` events of this process run" — never "did not happen". Anyone
         *     reconciling a custodial incident must go to the store, not here.
         *
         *     The ring is per camera rather than global on purpose, so that a busy camera can
         *     only evict its own history and never a quiet camera's.
         *
         *     `latest` is the last element of `events`, lifted out for the live scene panel and
         *     read from the same snapshot, so the panel and the chart cannot disagree about
         *     which event is newest. `latest_description_state` distinguishes the three cases a
         *     console must not confuse: `none` (nothing assembled yet in this process),
         *     `available` (a real vision-model description), and `unavailable` (the vision model
         *     could not answer, and `latest.description` is a metadata-derived stand-in rather
         *     than a description of the scene).
         *
         *     An unknown camera is a 404, the same mapping every other camera route uses. A
         *     configured camera that has not escalated yet is a 200 with an empty `events` list.
         */
        get: operations["get_camera_events_cameras__camera_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{camera_id}/telemetry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Camera Telemetry */
        get: operations["get_camera_telemetry_cameras__camera_id__telemetry_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live event stream (SSE) over the same volatile ring — NOT the event store
         * @description Every camera's anomaly events, pushed as they happen (spec §6.2, bridged).
         *
         *     **The same volatile, bounded, in-memory ring `GET /cameras/{camera_id}/events`
         *     serves — not the event store and not an audit trail.** The durable record is the
         *     anomaly event published to RabbitMQ and written down by the Phase 1C consumer.
         *     Everything this stream can send is held in engine memory, is lost on restart, and
         *     is silently evicted once a camera has produced more than `capacity` events.
         *
         *     **What a reconnect can and cannot give you.** Every connection opens with a
         *     `backlog` frame holding what the ring currently has, then continues live. There is
         *     no gap between the two and no duplicate across them. But the ring is bounded, so a
         *     client that was disconnected long enough for a camera to produce more than its
         *     ring holds **has permanently missed those events on this endpoint** — they are in
         *     RabbitMQ, and this endpoint will never show them. That is why no `id:` field is
         *     sent and `Last-Event-ID` is not honoured: resuming from an offset the engine may
         *     no longer hold would promise a continuity it cannot keep. Reconnect, take the new
         *     backlog as the current window, and go to the store for anything older.
         *
         *     **Duplicates and updates.** An `event_id` may arrive more than once: an event is
         *     re-sent when something about it changes, currently when its clip finishes and
         *     `clip_uri` appears. Merge by `event_id`, keeping the copy with the higher
         *     `sequence`. Two copies with the same `sequence` are the same copy.
         *
         *     **Falling behind.** A client that stops reading is buffered up to a fixed bound
         *     and then cut off with an `overflow` frame rather than being allowed to grow the
         *     engine's memory. Reconnect; the fresh backlog is more current than the queue that
         *     was dropped.
         *
         *     **Shutdown.** The engine closes every stream as it shuts down, so a client sees a
         *     clean end of response rather than a connection that hangs until a proxy times it
         *     out.
         */
        get: operations["stream_events_events_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CameraEventsResponse
         * @description A **volatile, bounded, in-memory view for the operator console. Not the event
         *     store, and not an audit trail.**
         *
         *     The durable record of what happened is RabbitMQ plus the Phase 1C consumer that
         *     writes it down. This endpoint reads an in-process ring that (a) is emptied by any
         *     restart of the engine, and (b) silently discards a camera's oldest entry once that
         *     camera has produced more than `capacity` events. An absent event here therefore
         *     means "not in the last `capacity` events of this process run" and never "did not
         *     happen". Do not reconcile against it, do not report from it, and do not use it to
         *     establish that nothing occurred.
         */
        CameraEventsResponse: {
            /** Camera Id */
            camera_id: string;
            /**
             * Capacity
             * @description The per-camera ring bound. Once `returned` reaches it, every new event silently evicts the oldest — published here so a console can say how much history it is not showing.
             */
            capacity: number;
            /**
             * Events
             * @description Retained events, oldest first — plot them in this order.
             */
            events: components["schemas"]["RecentEventEntry"][];
            /** @description The most recent event, i.e. the last element of `events`, lifted out for the live scene panel. Read from the same snapshot as `events`, so the panel and the chart can never disagree about which event is newest. Null exactly when `latest_description_state` is 'none'. */
            latest: components["schemas"]["RecentEventEntry"] | null;
            /**
             * Latest Description State
             * @description Whether the live panel has a real description ('available'), a stand-in because the vision model could not answer ('unavailable'), or nothing at all yet ('none').
             * @enum {string}
             */
            latest_description_state: "none" | "available" | "unavailable";
            /**
             * Returned
             * @description How many events this response carries.
             */
            returned: number;
            /**
             * Volatile
             * @description Always true, and present so it cannot be overlooked: this history is held in engine memory only and does not survive a restart. The event store is elsewhere.
             * @default true
             * @constant
             */
            volatile: true;
        };
        /** CameraStatus */
        CameraStatus: {
            /** Camera Id */
            camera_id: string;
            /** Detections Run */
            detections_run: number;
            /** Discontinuities */
            discontinuities: number;
            /** Escalations */
            escalations: number;
            /** Escalations Dropped */
            escalations_dropped: number;
            /** Frames Dropped */
            frames_dropped: number;
            /** Frames Seen */
            frames_seen: number;
            /** Last Escalation At */
            last_escalation_at: number | null;
            /** Last Frame At */
            last_frame_at: number | null;
            /** @description Which space this camera watches — the field cameras are grouped by. Null means ungrouped: nobody has assigned this camera a zone. Null is not a group; do not render it as one alongside the real zones. */
            zone?: components["schemas"]["Zone"] | null;
            /** @description The coarse grouping `zone` falls into, derived from it and never stored separately, so the two cannot disagree. Null exactly when `zone` is null. */
            zone_kind?: components["schemas"]["ZoneKind"] | null;
        };
        /** CamerasResponse */
        CamerasResponse: {
            /** Cameras */
            cameras: components["schemas"]["CameraStatus"][];
        };
        /** DescribeResponse */
        DescribeResponse: {
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Models */
            models: components["schemas"]["ModelHealth"][];
            /** Status */
            status: string;
        };
        /** ModelHealth */
        ModelHealth: {
            /** Detail */
            detail: string;
            /** Key */
            key: string;
            /** State */
            state: string;
            /** Vram Mib */
            vram_mib: number;
        };
        /**
         * RecentEventEntry
         * @description One event as the console sees it — a projection of the published anomaly event,
         *     not the event itself.
         *
         *     The same shape is served three ways: in `GET /cameras/{camera_id}/events`, in the
         *     `backlog` array that opens `GET /events/stream`, and in each live frame on that
         *     stream. One shape on purpose, so a console can merge all three into one list
         *     keyed by `event_id`, keeping the copy with the highest `sequence`.
         */
        RecentEventEntry: {
            /**
             * Camera Id
             * @description Which camera produced this. Redundant on the per-camera endpoint, and essential on `/events/stream`, which carries every camera's events.
             */
            camera_id: string;
            /**
             * Clip Uri
             * @description Where this event's clip was written, or null. Null covers three different situations and is not by itself evidence of any one of them: no clip was being recorded, the clip has not finished uploading yet (it lands shortly after the event, and the event is then re-sent on the stream with a higher `sequence`), or the clip failed to write. An event is never withheld because its clip failed — spec §9 — so a null here says nothing at all about whether the event happened.
             */
            clip_uri: string | null;
            /**
             * Description
             * @description The scene description — unless `description_unavailable` is true, in which case this is a metadata-derived stand-in and not a description of the scene.
             */
            description: string;
            /**
             * Description Unavailable
             * @description True when the vision model could not answer and this event was assembled from cheap signals alone. Never conflate it with the absence of an event.
             */
            description_unavailable: boolean;
            /**
             * Event Id
             * Format: uuid
             */
            event_id: string;
            /** Labels */
            labels: string[];
            /**
             * Occurred At
             * @description Unix epoch seconds (UTC, fractional). Sort and plot on this — it is the same field, with the same meaning, as the published event's `occurred_at`.
             */
            occurred_at: number;
            /**
             * Reason
             * @description Which of the seven escalation triggers fired.
             */
            reason: string;
            /**
             * Sequence
             * @description This version's position in the engine's write order for the recent-event ring — a de-duplication key, never a sort key. An event can be sent more than once with the same `event_id`: it is re-sent when something about it changes, currently when its clip finishes uploading and `clip_uri` appears. The copy with the higher `sequence` is the newer one; two copies with the same `sequence` are the same copy. Per process and monotonic — it restarts from zero when the engine does, exactly like the ring itself, so never persist it or compare it across a restart.
             */
            sequence: number;
            /**
             * Severity
             * @description The band `threat_score` falls in.
             */
            severity: string;
            /**
             * Source Timestamp
             * @description The camera source's own timeline for the same instant. Correlates with a clip's pts; meaningful only within one process run for one camera, so never sort or display on it.
             */
            source_timestamp: number | null;
            /** Suggested Action */
            suggested_action: string;
            /**
             * Threat Score
             * @description The threat value, 0.0 to 1.0.
             */
            threat_score: number;
            /** Track Ids */
            track_ids: number[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * Zone
         * @description The space a camera watches. The recorder's `space_type` vocabulary, exactly.
         *
         *     Deliberately the recorder's four-camera vocabulary rather than a new one: the two
         *     systems watch the same building, and a console that shows both must not have to
         *     translate. Extending it is a one-line addition here plus its entry in `_KINDS`,
         *     which `tests/domain/test_zone.py` requires for every member.
         * @enum {string}
         */
        Zone: "room" | "corridor" | "dayroom";
        /**
         * ZoneKind
         * @description The coarse privacy/behaviour split a `Zone` falls into.
         *
         *     Derived from `Zone`, never stored: see this module's docstring. `StrEnum` so it
         *     serialises as `"room"` / `"common_area"` with no encoder of its own.
         * @enum {string}
         */
        ZoneKind: "room" | "common_area";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cameras_cameras_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CamerasResponse"];
                };
            };
        };
    };
    describe_camera_now_cameras__camera_id__describe_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DescribeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_events_cameras__camera_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraEventsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_telemetry_cameras__camera_id__telemetry_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_events_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An open `text/event-stream`. Frames: `event: backlog` once, carrying a JSON array of RecentEventEntry (oldest first, possibly empty); then `event: anomaly`, one RecentEventEntry each, as they are assembled; `event: overflow` if this client fell too far behind, after which the stream ends and reconnecting is the recovery; and `: keepalive` comment lines on an idle stream. No `id:` field is sent and `Last-Event-ID` is not honoured — see the description. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            /** @description The engine has not finished starting; retry shortly. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
