"""Exports the REST control plane's OpenAPI document (spec §3.2).

    python -m sentinel_ai.openapi_export

Writes `contracts/openapi/ai-engine.yaml`, beside the event schema in
`contracts/events/`. `tests/test_openapi_contract.py` fails when the committed file
and the live app disagree, so the drift check is part of the ordinary test run rather
than a CI step someone has to remember to add.

This is the interface Phase 1C's Go backend consumes, and it could not exist before
`sentinel_ai/main.py` did: generating it needs a module-level `app`, and until the
composition root there was none. Building it needs no GPU, no camera file and no
broker — `ComposedService` constructs nothing until `start()`.

The document describes the *shape* of the four endpoints. Auth, pagination and a
common error envelope are deliberately not here: nothing in Phase 1B has them, and
inventing them in a contract the consumer will be generated from would be worse than
their absence.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

OPENAPI_PATH = Path(__file__).resolve().parents[2] / "contracts" / "openapi" / "ai-engine.yaml"


def openapi_document() -> dict[str, Any]:
    """The live app's OpenAPI document.

    Imported here rather than at module scope so that merely importing this module
    does not build a FastAPI app.
    """
    from sentinel_ai.main import app

    document: dict[str, Any] = app.openapi()
    return document


def render(document: dict[str, Any]) -> str:
    """YAML, deterministically. `sort_keys=True` is what makes the committed file a
    reviewable diff rather than a re-ordering every time FastAPI walks the routes in
    a different order."""
    import yaml

    header = (
        "# Generated by `python -m sentinel_ai.openapi_export` — do not edit by hand.\n"
        "# Spec §3.2: the committed document must not drift from the running app;\n"
        "# `tests/test_openapi_contract.py` fails the build when it does.\n"
    )
    body: str = yaml.safe_dump(document, sort_keys=True, default_flow_style=False, width=100)
    return header + body


def main() -> None:
    OPENAPI_PATH.parent.mkdir(parents=True, exist_ok=True)
    OPENAPI_PATH.write_text(render(openapi_document()), encoding="utf-8")
    print(f"wrote {OPENAPI_PATH}")


if __name__ == "__main__":
    main()
